//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSalesOrderList.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSalesOrderList.App_GlobalResources.AuthResources", typeof(AuthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   サインインＩＤまたはパスワードが無効または誤っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード有効期限が切れており、数回の変更要求がスキップされたためにサインインは行えません。パスワードのリセットを実施してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthPasswordNoChange {
            get {
                return ResourceManager.GetString("AuthPasswordNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーのサインインは許可されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthUserDisabled {
            get {
                return ResourceManager.GetString("AuthUserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーはロックアウトされています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthUserLockedOut {
            get {
                return ResourceManager.GetString("AuthUserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインインに所定の回数失敗したため、アカウントがロックアウトされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthUserLockedOutNow {
            get {
                return ResourceManager.GetString("AuthUserLockedOutNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   serverlog@j-fla.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailFrom {
            get {
                return ResourceManager.GetString("EmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jfla0001 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   serverlog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailUserName {
            get {
                return ResourceManager.GetString("EmailUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ不正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_1 {
            get {
                return ResourceManager.GetString("LogMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除済みユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_2 {
            get {
                return ResourceManager.GetString("LogMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックアウトユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_3 {
            get {
                return ResourceManager.GetString("LogMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用許可の無いユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_4 {
            get {
                return ResourceManager.GetString("LogMessage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードスキップＮＧ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_5 {
            get {
                return ResourceManager.GetString("LogMessage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックアウトされた に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_6 {
            get {
                return ResourceManager.GetString("LogMessage_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＩＤ／パスワードの誤り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage_7 {
            get {
                return ResourceManager.GetString("LogMessage_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインイン成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage0 {
            get {
                return ResourceManager.GetString("LogMessage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage1 {
            get {
                return ResourceManager.GetString("LogMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage2 {
            get {
                return ResourceManager.GetString("LogMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage3 {
            get {
                return ResourceManager.GetString("LogMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスの変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage4 {
            get {
                return ResourceManager.GetString("LogMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogMessage5 {
            get {
                return ResourceManager.GetString("LogMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスの確認依頼を受け付けました。\r\n以下に記載されているＵＲＬにアクセスしていただき、メールアドレスの確認を実施してください。\r\n\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailConfirmBody {
            get {
                return ResourceManager.GetString("MailConfirmBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスの確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailConfirmSubject {
            get {
                return ResourceManager.GetString("MailConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードのリセット処理の依頼を受け付けました。\r\n\r\n以下に記載されているＵＲＬにアクセスしていただき、パスワードのリセットを行ってください。\r\n\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailResetPasswordBody {
            get {
                return ResourceManager.GetString("MailResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードリセット依頼受付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailResetPasswordSubject {
            get {
                return ResourceManager.GetString("MailResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のパスワードと同じものは使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordChangeSame {
            get {
                return ResourceManager.GetString("PasswordChangeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインインＩＤもしくはメールアドレスのいずれかを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestMailNoParam {
            get {
                return ResourceManager.GetString("RequestMailNoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestMailNoUser {
            get {
                return ResourceManager.GetString("RequestMailNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のユーザーが見つからないかメール確認が行われていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPasswordNoUserOrNoConfirm {
            get {
                return ResourceManager.GetString("ResetPasswordNoUserOrNoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms37.kagoya.net に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SmtpHost {
            get {
                return ResourceManager.GetString("SmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   587 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
    }
}
