//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSalesOrderList.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSalesOrderList.App_GlobalResources.ContextResources", typeof(ContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SELECT SV.product_id AS product_id ,SV.detail_date AS detail_date ,SUM(SV.zaiko_actual) AS zaiko_actual ,SUM(SV.order_plan) AS order_plan ,SUM(SV.order_actual) AS order_actual ,SUM(SV.invoice_plan) AS invoice_plan ,SUM(SV.invoice_actual) AS invoice_actual ,SUM(SV.invoice_zan) AS invoice_zan ,SUM(SV.pre_sales_Actual) AS pre_sales_Actual ,SUM(SV.sales_plan) AS sales_plan ,SUM(SV.sales_actual) AS sales_actual ,SUM(SV.sales_trend) AS sales_trend FROM ( SELECT stc.product_id AS product_id ,stc.detail_date AS det [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _SelectDownloadData {
            get {
                return ResourceManager.GetString("_SelectDownloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT sls.product_id AS product_id ,sls.detail_date AS detail_date ,ofs.id AS office_id ,ofs.name AS office_name ,IFNULL(sls.plan,0) AS sales_plan ,IFNULL(sls.actual,0) AS sales_actual FROM sales sls INNER JOIN offices ofs ON sls.office_id = ofs.id WHERE sls.detail_date &gt;= DATE_ADD(@p0, INTERVAL -1 YEAR) AND sls.detail_date &lt; DATE_ADD(@p0, INTERVAL 18 MONTH) AND sls.product_id IN (@p1) AND sls.deleted = 0 AND ofs.deleted = 0 AND ofs.code &lt;&gt; &apos;**&apos; ORDER BY sls.detail_date ,ofs.id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _SelectDownloadOfficeData {
            get {
                return ResourceManager.GetString("_SelectDownloadOfficeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALTER TABLE groups AUTO_INCREMENT=1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncrementResetGroup {
            get {
                return ResourceManager.GetString("IncrementResetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALTER TABLE groups_products AUTO_INCREMENT=1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncrementResetGroupProduct {
            get {
                return ResourceManager.GetString("IncrementResetGroupProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALTER TABLE sales_trends AUTO_INCREMENT=1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncrementResetSalesTrend {
            get {
                return ResourceManager.GetString("IncrementResetSalesTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALTER TABLE users_makers AUTO_INCREMENT=1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncrementResetUserMaker {
            get {
                return ResourceManager.GetString("IncrementResetUserMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT sls.product_id AS product_id ,sls.detail_date AS detail_date ,ofs.id AS office_id ,ofs.name AS office_name ,IFNULL(sls.plan,0) AS sales_plan ,IFNULL(sls.actual,0) AS sales_actual FROM sales sls INNER JOIN offices ofs ON sls.office_id = ofs.id WHERE sls.detail_date &gt;= @p0 AND sls.detail_date &lt; @p1 AND sls.product_id IN (@p2)  AND sls.deleted = 0 AND ofs.deleted = 0 AND ofs.code &lt;&gt; &apos;**&apos; ORDER BY sls.detail_date ,ofs.id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectOfficeSalesViews {
            get {
                return ResourceManager.GetString("SelectOfficeSalesViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT OV.product_id ,OV.detail_date ,OV.office_id ,ofs.name ,SUM(OV.sales_plan) AS sales_plan ,SUM(OV.sales_actual) AS sales_actual ,SUM(OV.pre_sales_plan) AS pre_sales_plan ,SUM(OV.pre_sales_actual) AS pre_sales_actual FROM ( SELECT sls.product_id AS product_id ,sls.detail_date AS detail_date ,sls.office_id AS office_id ,IFNULL(sls.plan,0) AS sales_plan ,IFNULL(sls.actual,0) AS sales_actual ,0 AS pre_sales_plan ,0 AS pre_sales_actual FROM sales sls WHERE sls.detail_date &gt;= @p0 AND sls.detail_date &lt; @p1 AN [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectOfficesSalesViews {
            get {
                return ResourceManager.GetString("SelectOfficesSalesViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT SV.product_id AS product_id ,SV.detail_date AS detail_date ,SUM(SV.zaiko_actual) AS zaiko_actual ,SUM(SV.order_plan) AS order_plan ,SUM(SV.order_actual) AS order_actual ,SUM(SV.invoice_plan) AS invoice_plan ,SUM(SV.invoice_actual) AS invoice_actual ,SUM(SV.invoice_zan) AS invoice_zan ,SUM(SV.invoice_adjust) AS invoice_adjust ,SUM(SV.pre_sales_actual) AS pre_sales_actual ,SUM(SV.sales_plan) AS sales_plan ,SUM(SV.sales_actual) AS sales_actual ,SUM(SV.sales_trend) AS sales_trend FROM ( SELECT stc.produc [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectSalesViews {
            get {
                return ResourceManager.GetString("SelectSalesViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO application_logs (processing_date,process_name,user_id,message) VALUES (@p0,@p1,@p2,@p3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WriteLogSql {
            get {
                return ResourceManager.GetString("WriteLogSql", resourceCulture);
            }
        }
    }
}
