//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSalesOrderList.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSalesOrderList.App_GlobalResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   パラメーターが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiIllegalParameter {
            get {
                return ResourceManager.GetString("ApiIllegalParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメーターがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiNoParameter {
            get {
                return ResourceManager.GetString("ApiNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   for ARCANE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationComment {
            get {
                return ResourceManager.GetString("ApplicationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発注在庫管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫・販売状況確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton01 {
            get {
                return ResourceManager.GetString("MainMenuButton01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予算データアップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton02 {
            get {
                return ResourceManager.GetString("MainMenuButton02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当メーカー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton03 {
            get {
                return ResourceManager.GetString("MainMenuButton03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton04 {
            get {
                return ResourceManager.GetString("MainMenuButton04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton05 {
            get {
                return ResourceManager.GetString("MainMenuButton05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理機能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton06 {
            get {
                return ResourceManager.GetString("MainMenuButton06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインインログ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton07 {
            get {
                return ResourceManager.GetString("MainMenuButton07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクションログ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuButton08 {
            get {
                return ResourceManager.GetString("MainMenuButton08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedGroupEdit {
            get {
                return ResourceManager.GetString("ManagedGroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ商品編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedGroupProduct {
            get {
                return ResourceManager.GetString("ManagedGroupProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedMenuButton00 {
            get {
                return ResourceManager.GetString("ManagedMenuButton00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedMenuButton01 {
            get {
                return ResourceManager.GetString("ManagedMenuButton01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メーカー管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedMenuButton02 {
            get {
                return ResourceManager.GetString("ManagedMenuButton02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedMenuButton03 {
            get {
                return ResourceManager.GetString("ManagedMenuButton03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedMenuButton04 {
            get {
                return ResourceManager.GetString("ManagedMenuButton04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedProductEdit {
            get {
                return ResourceManager.GetString("ManagedProductEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedUserEdit {
            get {
                return ResourceManager.GetString("ManagedUserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーメーカー編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedUserMaker {
            get {
                return ResourceManager.GetString("ManagedUserMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー新規登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedUserNew {
            get {
                return ResourceManager.GetString("ManagedUserNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーロール編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManagedUserRole {
            get {
                return ResourceManager.GetString("ManagedUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象メーカー選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesViewScreen01 {
            get {
                return ResourceManager.GetString("SalesViewScreen01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象グループ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesViewScreen02 {
            get {
                return ResourceManager.GetString("SalesViewScreen02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫販売情報一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesViewScreen03 {
            get {
                return ResourceManager.GetString("SalesViewScreen03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品明細表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesViewScreen04 {
            get {
                return ResourceManager.GetString("SalesViewScreen04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売動向登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesViewScreen05 {
            get {
                return ResourceManager.GetString("SalesViewScreen05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}と{1}が一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidateCompare {
            get {
                return ResourceManager.GetString("ValidateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は正しいメールアドレス形式ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上で入力をして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidateMaxLength {
            get {
                return ResourceManager.GetString("ValidateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以下で入力をして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidateMinLength {
            get {
                return ResourceManager.GetString("ValidateMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidateRequired {
            get {
                return ResourceManager.GetString("ValidateRequired", resourceCulture);
            }
        }
    }
}
